#!/usr/bin/env bash

# Set script dir to pwd
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Make sure user has exported $DEV_ENV
if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

# if i just did DEV_ENV=$(pwd) ./run then this is needed for the rest of the
# scripts
export DEV_ENV="$DEV_ENV"

grep=""
dry_run="0"

# While more than one argument
while [[ $# -gt 0 ]]; do
    # Print the argument
    echo "ARG: \"$1\""

    # If the argument is "--dry" set dry ryn
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    # else set arg to grep
    else
        grep="$1"
    fi
    # push the arg off the stack to go to next arg
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: env: $env -- grep: $grep"

# find all of our bash scripts in script_dir/runs
runs_dir=`find $script_dir/runs -mindepth 1 -maxdepth 1 -executable`

# for each bash file
for s in $runs_dir; do
    # log if script does not match passed arg; skip script
    if echo "$s" | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $s"
        continue
    fi


    # Log which script we're running (and if it's a dry run)
    log "running script: $s"

    # If this is not a dry run, actually run the script, else don't run
    if [[ $dry_run == "0" ]]; then
        $s
    fi
done

#remove_files() {
#    pushd $1
#    (
#        configs=`find . -mindepth 1 -maxdepth 1 -type d`
#        if [[ $dry_run == "1" ]]; then
#            echo "[DRY_RUN]: removing: $configs"
#        else
#            echo "removing: $configs"
#        fi
#
#        for c in $configs; do
#            directory=${2%/}/${c}
#            if [[ $dry_run == "1" ]]; then
#                echo "[DRY_RUN]:    removing: $directory"
#            else
#                echo "    removing: $directory"
#                rm -rf $directory
#            fi
#        done
#
#        if [[ $dry_run == "1" ]]; then
#            echo "copying env: $2"
#        else
#            echo "copying env: $2"
#            cp -r ./* $2
#        fi
#    )
#    popd
#}

#run_env() {
#    pushd $script_dir
#    echo "removing ~config"
#    remove_files env/.config $XDG_CONFIG_HOME
#
#    echo "removing ~local"
#    remove_files env/.local $HOME/.local
#
#    echo "copying zsh"
#    if [[ $dry_run == "0" ]]; then
#        cp $script_dir/env/.zshrc ~/.zshrc
#        cp $script_dir/env/.zsh_profile ~/.zsh_profile
#    fi
#
#    popd
#}
