#!/usr/bin/env bash

# Prime's config didn't work... :()
# sudo apt install nodejs npm
# npm config set prefix ~/.local/npm
# npm i -g n
# n lts

# Used for writing JS/TS code
# https://nodejs.org/en/download

# Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

# in lieu of restarting the shell
\. "$HOME/.nvm/nvm.sh"

# Download and install Node.js:
nvm install 22

# Verify the Node.js version:
node -v # Should print "v22.15.0".
nvm current # Should print "v22.15.0".

# Verify npm version:
npm -v # Should print "10.9.2".


# curl -fsSL https://deno.land/install.sh | sh
# curl -fsSL https://bun.sh/install | bash
